"""init model

Revision ID: 58f6e65eb66d
Revises: 
Create Date: 2026-04-28 00:22:04.074322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58f6e65eb66d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_days > 0', name='duration_days_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_slug'), 'trips', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PASSENGER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('departures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('price_per_seat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity > 0', name='capacity_positive'),
    sa.CheckConstraint('price_per_seat > 0', name='price_per_seat_positive'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name='fk_departure_trip'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departures_trip_id'), 'departures', ['trip_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('departure_id', sa.Integer(), nullable=False),
    sa.Column('seats_reserved', sa.Integer(), nullable=False),
    sa.Column('price_per_seat_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('RESERVED', 'CANCELLED', 'CONFIRMED', 'EXPIRED', name='booking_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payment_deadline', sa.Date(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('price_per_seat_snapshot >= 0', name='price_per_seat_snapshot_non_negative'),
    sa.CheckConstraint('seats_reserved >= 1 AND seats_reserved <= 10', name='seats_reserved_range'),
    sa.CheckConstraint('total_price_snapshot >= 0', name='total_price_snapshot_non_negative'),
    sa.ForeignKeyConstraint(['departure_id'], ['departures.id'], name='fk_booking_departure'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_booking_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_departure_id'), 'bookings', ['departure_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_departure_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_departures_trip_id'), table_name='departures')
    op.drop_table('departures')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trips_slug'), table_name='trips')
    op.drop_table('trips')
    # ### end Alembic commands ###
